export const GET_USER_LOGIN = 'GET_USER_LOGIN';
export const UPDATE_TICKET = 'UPDATE_TICKET';
export const ADD_VISITOR_TYPE_CART = 'ADD_VISITOR_TYPE_CART';
export const REMOVE_VISITORTYPE = 'REMOVE_VISITORTYPE';
export const ADD_VISITOR_TYPE_CART_ALL = 'ADD_VISITOR_TYPE_CART_ALL';
export const SHOW_LOADER = 'SHOW_LOADER';
export const HIDE_LOADER = 'HIDE_LOADER';
export const SHOW_LOADER_PART = 'SHOW_LOADER_PART';
export const HIDE_LOADER_PART = 'HIDE_LOADER_PART';
export const GET_ALL_CATEGORY = 'GET_ALL_CATEGORY';
export const GET_ALL_CITY = 'GET_ALL_CITY';
export const REMOVE_USER_LOGIN = 'REMOVE_USER_LOGIN';
export const CHECK_TOKEN_LOGIN = 'CHECK_TOKEN_LOGIN';
export const REMOVE_ALL_VISITORTYPE_QUANTITY_EQUAL_ZERO = 'REMOVE_ALL_VISITORTYPE_QUANTITY_EQUAL_ZERO';


