export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const ADD_CATEGORIES = 'ADD_CATEGORIES';
export const UPDATE_CATEGORIES = 'UPDATE_CATEGORIES';
export const DELETE_CATEGORIES = 'DELETE_CATEGORIES';
export const EDIT_CATEGORY = 'EDIT_CATEGORY';