export const FETCH_PAYMENT_METHOD_TYPES = 'FETCH_PAYMENT_METHOD_TYPES';
export const ADD_PAYMENT_METHOD_TYPES = 'ADD_PAYMENT_METHOD_TYPES';
export const UPDATE_PAYMENT_METHOD_TYPES = 'UPDATE_PAYMENT_METHOD_TYPES';
export const DELETE_PAYMENT_METHOD_TYPES = 'DELETE_PAYMENT_METHOD_TYPES';
export const EDIT_PAYMENT_METHOD_TYPE = 'EDIT_PAYMENT_METHOD_TYPE';