export const FETCH_PLACES = 'FETCH_PLACES';
export const ADD_PLACE = 'ADD_PLACE';
export const UPDATE_PLACE = 'UPDATE_PLACE';
export const CHANGE_STATUS_PLACE = 'CHANGE_STATUS_PLACE';
export const DELETE_PLACE = 'DELETE_PLACE';
export const EDIT_PLACE = 'EDIT_PLACE';
export const FETCH_PLACE_TYPES = 'FETCH_PLACE_TYPES';
