export const FETCH_TICKET_TYPES = 'FETCH_TICKET_TYPES';
export const ADD_TICKET_TYPES = 'ADD_TICKET_TYPES';
export const UPDATE_TICKET_TYPES = 'UPDATE_TICKET_TYPES';
export const DELETE_TICKET_TYPES = 'DELETE_TICKET_TYPES';
export const EDIT_TICKET_TYPE = 'EDIT_TICKET_TYPE';