export const ADD_VISISTOR_TYPES = 'ADD_VISISTOR_TYPES';
export const UPDATE_VISISTOR_TYPES = 'UPDATE_VISISTOR_TYPES';
export const DELETE_VISISTOR_TYPES = 'DELETE_VISISTOR_TYPES';
export const EDIT_VISISTOR_TYPE = 'EDIT_VISISTOR_TYPE';